### ISSUE TITLE
[Error] Library not loaded: bazel-out/darwin_x86_64-opt/bin/tensorflow/libtensorflow.so

### ISSUE THREAD

**Issue by yuanyan** [yorkie/tensorflow-nodejs#25]
When run in MacOS, throw a error:
```
Error: dlopen(/Users/xxx/node_modules/tensorflow2/build/Release/tensorflow.node, 1): Library not loaded: bazel-out/darwin_x86_64-opt/bin/tensorflow/libtensorflow.so
  Referenced from: /Users/xxx/node_modules/tensorflow2/build/Release/tensorflow.node
  Reason: image not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/xxx/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/xxx/node_modules/tensorflow2/lib/index.js:5:56)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

I copy the libtensorflow.so file into project root directory (myproject/bazel-out/darwin_x86_64-opt/bin/tensorflow/libtensorflow.so) sloved this error.

**Comment by yorkie** [comment]
Yea, it's MacOS-specific problem, https://github.com/yorkie/tensorflow-nodejs/blob/master/binding.gyp#L27 not working at OSX.

**Comment by jaafarskafi1** [comment]
where would I be able to find the `libtensorflow.so` file? I did not use bazel in compiling/generating my tensorflow graph.

**Comment by yorkie** [comment]
@jaafarskafi1 this should be another topic about your question.

> where would you be able to find the `libtensorflow.so` file?

See https://github.com/yorkie/tensorflow-nodejs/blob/master/binding.gyp#L26-L30, just put the library to those dirs.

> I do have the pre-trained graph on hand

What you need is [run a predefined graph](https://github.com/yorkie/tensorflow-nodejs#run-a-predefined-graph)?
