### ISSUE TITLE
Image.decodeJpeg

### ISSUE THREAD

**Issue by csibesz07** [yorkie/tensorflow-nodejs#27]
```
var tf = require('tensorflow2');
var fs = require('fs');

const graph = tf.graph();
const session = tf.session();

let image = fs.readFileSync(process.cwd() + "/example.jpg").toString('base64');
let imageTensor = tf.tensor(image, tf.dtype.string);
let imageConstant = graph.constant(imageTensor);
let result = graph.image.decodeJpeg(imageConstant); //line 10, input is an Operation
```

Error:

```
2017-10-14 12:30:09.064477: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
S:\Electron\tensorflow-nodejs\lib\graph.js:146
      op.finish();
         ^

Error
    at Error (native)
    at Graph.createOperationFromBuilder (S:\Electron\tensorflow-nodejs\lib\graph.js:146:10)
    at Object.<anonymous> (S:\Electron\tensf2-test\index.js:10:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

Another question: is it possible to use Tensorflow Object Detection API with this library?
[object_detection_tutorial.ipynb](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb)

System: 
Windows 10 64bit
Visual C++ Build Tools 2015

Used package for windows:
[libtensorflow-cpu-windows-x86_64-1.4.0-rc0.zip](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.4.0-rc0.zip)

**Comment by yorkie** [comment]
The error says:

```
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
S
```

Take a look at this link: https://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions, and https://github.com/tensorflow/tensorflow/issues/8037.

Closing this one now because this is not an issue of this binding library, feel free to comment if any question again :)
