### ISSUE TITLE
No support for your platform win32

### ISSUE THREAD

**Issue by digimbyte** [yorkie/tensorflow-nodejs#35]
Got a new typescript project going, and I ran into this issue installing tensorflow2
`No support for your platform win32`

I am fairly confident that I am running 64 windows 10
I tried running the command inside VS Code and Powershell

Full Error
```
D:\development\rader\node_modules\@pipcook\boa\tools\check-dependence.js:16
  throw new TypeError(`No support for your platform ${PLATFORM}`);
  ^

TypeError: No support for your platform win32
    at Object.<anonymous> (D:\development\rader\node_modules\@pipcook\boa\tools\check-dependence.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm WARN @uniswap/sdk@3.0.3 requires a peer of @ethersproject/address@^5.0.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN @uniswap/sdk@3.0.3 requires a peer of @ethersproject/contracts@^5.0.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN @uniswap/sdk@3.0.3 requires a peer of @ethersproject/networks@^5.0.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN @uniswap/sdk@3.0.3 requires a peer of @ethersproject/providers@^5.0.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN @uniswap/sdk@3.0.3 requires a peer of @ethersproject/solidity@^5.0.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN rader@1.0.0 No description
npm WARN rader@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pipcook/boa@1.3.0 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pipcook/boa@1.3.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\digim\AppData\Roaming\npm-cache\_logs\2021-02-07T07_56_52_487Z-debug.log
PS D:\development\rader>
```

**Comment by holopekochan** [comment]
Looks like this is from boa, https://github.com/imgcook/boa/issues/11
