### ISSUE TITLE
proto path to load fails

### ISSUE THREAD

**Issue by yorkie** [yorkie/tensorflow-nodejs#7]
The error log:

```
/Users/yorkie/workspace/tf-example/node_modules/protobufjs/src/root.js:94
            throw err;
            ^

Error: ENOENT: no such file or directory, open 'protobuf/config.proto'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at fetch (/Users/yorkie/workspace/tf-example/node_modules/protobufjs/src/root.js:160:34)
    at Root.load (/Users/yorkie/workspace/tf-example/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (/Users/yorkie/workspace/tf-example/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/Users/yorkie/workspace/tf-example/node_modules/protobufjs/src/index-light.js:69:17)
    at Object.<anonymous> (/Users/yorkie/workspace/tf-example/node_modules/tensorflow2/lib/index.js:10:30)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

To reproduce this bug, install this package via npm and `require('tensorflow')` on another directory except for the project root.

**Comment by yorkie** [comment]
This is because we are using `cwd` to load the proto files, just go to fix it :)

**Comment by yorkie** [comment]
Fixed at this commit: https://github.com/yorkie/tensorflow-nodejs/commit/a5d6fe9ed3cabfa5bb1683c110c40e90cfcba840
